name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 30
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.8", "3.9", "3.10"]
        services:
            # Label used to access the service container
            redis:
                # Docker Hub image
                image: redislabs/redis
                    # Set health checks to wait until redis has started
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    # Maps port 6379 on service container to the host
                    - 6379:6379
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Poetry
              uses: snok/install-poetry@v1
              with:
                  virtualenvs-in-project: true
                  virtualenvs-create: true
                  installer-parallel: true
            - name: Load cached venv if cache exists
              id: cached-poetry-deps
              uses: actions/cache@v3
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
            - name: Install dependencies
              if: steps.cached-poetry-deps.outputs.cache-hit != 'true'
              run: |
                  poetry install --no-interaction --no-root
            - name: Install Manifest
              run: |
                  make dev
            - name: Run preliminary checks
              run: |
                  make check
            - name: Test with pytest
              run: |
                  poetry run pytest tests