name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 30
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.10", "3.11"]
        services:
            # Label used to access the service container
            redis:
                # Docker Hub image
                image: redis
                    # Set health checks to wait until redis has started
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    # Maps port 6379 on service container to the host
                    - 6379:6379
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Manifest
              run: |
                  make dev
            - name: Run preliminary checks
              run: |
                  make check
            - name: Test with pytest
              run: |
                  pytest tests
